# -*- coding: utf-8 -*-
"""k_car_passenger_search.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DmmCq-421myyEMzltffhYhvjJfh8SZio
"""

import pandas as pd


print("巨人の持ち物検査中...")
df = pd.read_csv('vehicles.csv', on_bad_lines='skip', engine='python', nrows=100) # 最初は100行だけでOK


print("--- 見つかった列の名前一覧 ---")
print(df.columns.tolist())
print("----------------------------")

import pandas as pd

print("泥沼の中からお宝（列名）を探しています...")

try:
    df_check = pd.read_csv('vehicles.csv', skiprows=20, nrows=10, engine='python')
    print("--- 20行飛ばしてみた結果の列名 ---")
    print(df_check.columns.tolist())
except Exception as e:
    print(f"エラーが出ました: {e}")

import pandas as pd

print("巨人を強制捜査中...（今度は列の名前を自分で決めます）")

column_names = [
    'id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
    'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
    'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color',
    'image_url', 'description', 'county', 'state', 'lat', 'long', 'posting_date'
]

df = pd.read_csv(
    'vehicles.csv',
    skiprows=1,
    names=column_names,
    on_bad_lines='skip',
    engine='python'
)

k_car_keywords = [
    'wagon r', 'move', 'mira', 'pajero mini', 'jimny',
    'alto', 'life', 'estilo', 'vivio', 'pleo', 'cappuccino', 'beat', 'az-1'
]
pattern = '|'.join(k_car_keywords)

k_passenger_cars = df[
    (df['type'] != 'truck') &
    (
        df['model'].str.contains(pattern, case=False, na=False) |
        df['description'].str.contains(pattern, case=False, na=False) |
        df['description'].str.contains('660cc', case=False, na=False)
    )
].copy()

print(f"捜索完了！ {len(k_passenger_cars)} 台の『軽乗用車』を見つけました。")

k_passenger_cars.to_csv('k_passenger_cars_found.csv', index=False)
print("結果を 'k_passenger_cars_found.csv' に保存しました。")

"""前回の軽トラが54台だったのに対して、**26,020台**というのは桁違いです。もちろん、この中には「660cc」という数字に引っかかった別の車も混じっているかもしれませんが、アメリカにおける「日本の軽自動車文化」の潜伏数は、想像以上に巨大だということがデータで証明されました。

**26,020台の「中身」をのぞく**
"""

import pandas as pd

df_k = pd.read_csv('k_passenger_cars_found.csv')

check_list = [
    'wagon r', 'move', 'mira', 'pajero mini',
    'jimny', 'alto', 'cappuccino', 'beat', 'tanto'
]

print("--- アメリカで見つかった『軽』車種別ランキング ---")

for car_name in check_list:
    mask = (
        df_k['model'].str.contains(car_name, case=False, na=False) |
        df_k['description'].str.contains(car_name, case=False, na=False)
    )
    count = df_k[mask].shape[0]
    print(f"{car_name.upper():<15}: {count:>5} 台")

print("\n--- 軽自動車が集まっている州 TOP 10 ---")
print(df_k['state'].value_counts().head(10))

"""**データの「インサイト（洞察）」：なぜこんな結果に？**

**1. ムーヴ（MOVE）が圧倒的すぎる理由**
2.6万台のうち、半分以上の約1.4万台が「MOVE」。 これは単に人気があるだけでなく、アメリカの業者が**「日本のムーヴは安くて高品質な『動く箱（MOVE）』として最高だ！」**と確信して、コンテナで大量に運び込んでいる可能性があります。あるいは、"Move"（動く、引っ越し）という単語が説明文に混じっている可能性もありますが、それにしてもこの数字は圧倒的です。

**2. BEAT（ビート）とCAPPUCCINO（カプチーノ）の逆転劇**

日本ではカプチーノの方が人気が出ることも多いですが、アメリカではBEATが2,821台と圧勝。 「ホンダ・ビート」は、あのフェラーリと同じ「ミッドシップ」構造。アメリカのホンダ・マニアたちが、手の届くスーパーカーとして買い漁っている光景が目に浮かびます。

**3. TANTO（タント）の「365台」が一番やばい！**

バディ、ここが一番の驚きです。25年ルール（2001年製まで）を考えると、2003年発売のタントは本来まだアメリカで公道を走れないはずなんです。 それなのに365台もあるということは……：

**「あと数年で解禁されるお宝」**として、すでに業者が日本から仕入れて倉庫に寝かせている。

あるいは、農場などの**「私有地専用車」として、法律の壁を越えて既に輸入されている。 これは完全に「未来のトレンド」**を先取りしたデータです。

**4. 州のランキング：カリフォルニア（CA）が独走**

カリフォルニアは排ガス規制が全米一厳しいはずなのに、9,217台で1位。 「小さくてエコ」「狭いサンフランシスコの街に最適」という理由で、西海岸のオシャレな層に刺さっているのかもしれません。

**タントの正体は？**
"""

import pandas as pd
import os

original_file = 'k_passenger_cars_found.csv'

if os.path.exists(original_file):
    df_k = pd.read_csv(original_file)

    df_tanto = df_k[df_k['model'].str.contains('tanto', case=False, na=False)].copy()

    print(f"🔎 調査対象: {len(df_tanto)} 台の『TANTO』を見つけました！\n")

    for i, row in df_tanto.head(3).iterrows():
        print(f"【価格: ${row['price']} | 場所: {row['state']}】")
        print(f"内容: {str(row['description'])[:150]}...")
        print("-" * 50)
else:
    print(f"😱 エラー：'{original_file}' が見当たりません！")
    print("昨日1.4GBから抽出したCSVと同じ場所にこのプログラムを置いていますか？")

import pandas as pd

df_k = pd.read_csv('k_passenger_cars_found.csv')

mask = (df_k['model'].str.contains('tanto', case=False, na=False)) | \
       (df_k['description'].str.contains('tanto', case=False, na=False))

df_tanto_found = df_k[mask].copy()

print(f"📡 再捜査結果: {len(df_tanto_found)} 台の『TANTO』を検知！")

if len(df_tanto_found) > 0:
    print("\n--- 発見した個体の詳細 ---")
    for i, row in df_tanto_found.head(5).iterrows():
        print(f"Model: {row['model']} / Price: ${row['price']}")
        print(f"Description snippet: {str(row['description'])[:100]}...")
        print("-" * 30)
else:
    print("\n😱 完全に消えました。昨日使った『df_k』と中身が違うかもしれません...")

"""モデル名が pilot（ホンダ）や corolla（トヨタ）ばかりです。これ、私が好きだったダイハツのタントじゃありません。

スペイン語やイタリア語で 「en tanto（〜の間、その一方で、非常に）」 という定型文が、アメリカの中古車販売業者の決まり文句として説明文に大量に入っていたんです。

365台のタントの正体は中古車屋さんの宣伝文句

最後に本当に本物のタントが混じってないか調べる。「DAIHATSU（ダイハツ）」という言葉も一緒に含まれているものだけを
"""

real_tanto = df_tanto_found[df_tanto_found['description'].str.contains('daihatsu', case=False, na=False)]

print(f"真実のタント: {len(real_tanto)} 台")

if len(real_tanto) > 0:
  print("いたぞ！これが本物だ！")
  print(real_tanto[['model', 'price', 'description']])
else:
  print("全滅！すべてスペイン語の挨拶でした(笑) ")

"""**「真のインサイト」**

**データの「嘘」を見抜いた**: 「タントが365台もある、やばい！」という直感的な驚きを、自分の手で「あ、これゴミデータだ（笑）」という確信に変えた。これこそがデータサイエンスの成長そのものです。

**アメリカの地域性**: カリフォルニア（CA）やフロリダ（FL）など、スペイン語圏のユーザーが多い地域で「en tanto」というフレーズが多用されていたという背景も見えてきましたね。

**「MOVE」の信憑性が上がった**: タントが全滅した一方で、1.3万台もある「MOVE」の方は、その圧倒的な数からして本物の可能性が非常に高い（あるいは別の宣伝文句か？）という次の課題も見えてきました。

**MOVEの山を掘り返す**
"""

import pandas as pd

df_k = pd.read_csv('k_passenger_cars_found.csv')
df_move = df_k[df_k['model'].str.contains('move', case=False, na=False)]

print(f"📊 検知されたMOVE: {len(df_move)} 台")

real_move = df_move[df_move['description'].str.contains('daihatsu', case=False, na=False)]

if len(real_move) > 0:
    print(f"✨ おっ！本物のダイハツ・ムーヴが {len(real_move)} 台見つかりました！")
else:
    print("😱 1.3万台すべて『車以外のMOVE』の可能性大です...")

print("\n--- 説明文の抜き打ちチェック ---")
for i, row in df_move.head(3).iterrows():
    print(f"【内容】: {str(row['description'])[:150]}...")
    print("-" * 50)

import pandas as pd

df_k = pd.read_csv('k_passenger_cars_found.csv')

mask_move = (df_k['model'].str.contains('move', case=False, na=False)) | \
            (df_k['description'].str.contains('move', case=False, na=False))

df_move_all = df_k[mask_move].copy()

print(f"📡 再捜査結果: {len(df_move_all)} 台の『MOVE』を検知！")

if len(df_move_all) > 0:
    for i, row in df_move_all.head(3).iterrows():
        print(f"【Model: {row['model']} / Price: ${row['price']}】")
        print(f"内容: {str(row['description'])[:150]}...")
        print("-" * 50)

"""**なぜこれらが「MOVE」として検知されたのか？**

"Ready to move" （すぐ動かせます＝即納車可能です） "Must move fast" （早く売り払いたい）

タントの時はスペイン語でしたが、ムーヴの正体は**「中古車販売の決まり文句」**でした。1.4万台のムーヴ軍団は、残念ながら「すぐ動くよ！」と言っているだけの多種多様な車たちだった。

**「真実のムーヴ」を絞り出す**

# 14,850台の中から「本物のダイハツ」をあぶり出す
"""

real_daihatsu_move = df_move_all[df_move_all['description'].str.contains('daihatsu', case=False, na=False)]

print(f"🔥 真実のムーヴ: {len(real_daihatsu_move)} 台")

if len(real_daihatsu_move) > 0:
    print("いた！これがアメリカを走る本物のムーヴだ！")
    print(real_daihatsu_move[['model', 'price', 'description']])
else:
    print("全滅！1.4万台すべて『Ready to move』な別車両でした（笑）")

"""「1.4万台のムーヴ軍団」が、実は全員ただの**「やる気のある中古車（Ready to move）」**だったという

**TANTO**,365台,0台,スペイン語の挨拶 (en tanto)

**MOVE**,"14,850台",0台,販売文句 (Ready to move)

**「軽自動車はアメリカに（このサイト上には）ほぼいない」という事実**: 1.4GBもの巨大なデータの中を、あれだけ丁寧に探しても「0」だった。これは「アメリカで軽は超レア」という立派な統計データです。

**ノイズを見抜く力**: 普通の人なら「アメリカにはタントやムーヴが大量にある！」と勘違いして間違ったレポートを書くところを、バディは自分の力で真実の0に辿り着きました
"""